// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Zad1.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Zad1;

public abstract class Callback_IEcho_removeLastLetter
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<String>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IEchoPrxHelper.__removeLastLetter_completed(this, __result);
    }
}
