// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Zad1.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Zad1;

public interface IEcho extends Ice.Object,
                               _IEchoOperations, _IEchoOperationsNC
{
    public static final String ice_staticId = "::Zad1::IEcho";

    public static final long serialVersionUID = -4642346686571907301L;
}
