// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Zad1.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Zad1;

/**
 * Provides type-specific helper functions.
 **/
public final class IEchoPrxHelper extends Ice.ObjectPrxHelperBase implements IEchoPrx
{
    private static final String __appendString_name = "appendString";

    public String appendString(String toAppend)
    {
        return appendString(toAppend, null, false);
    }

    public String appendString(String toAppend, java.util.Map<String, String> __ctx)
    {
        return appendString(toAppend, __ctx, true);
    }

    private String appendString(String toAppend, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__appendString_name);
        return end_appendString(begin_appendString(toAppend, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_appendString(String toAppend)
    {
        return begin_appendString(toAppend, null, false, false, null);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, java.util.Map<String, String> __ctx)
    {
        return begin_appendString(toAppend, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, Ice.Callback __cb)
    {
        return begin_appendString(toAppend, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_appendString(toAppend, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, Callback_IEcho_appendString __cb)
    {
        return begin_appendString(toAppend, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, java.util.Map<String, String> __ctx, Callback_IEcho_appendString __cb)
    {
        return begin_appendString(toAppend, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_appendString(toAppend, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_appendString(toAppend, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_appendString(toAppend, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_appendString(toAppend, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_appendString(String toAppend, 
                                               java.util.Map<String, String> __ctx, 
                                               boolean __explicitCtx, 
                                               boolean __synchronous, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_appendString(toAppend, __ctx, __explicitCtx, __synchronous, 
                                  new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                      {
                                          public final void __completed(Ice.AsyncResult __result)
                                          {
                                              IEchoPrxHelper.__appendString_completed(this, __result);
                                          }
                                      });
    }

    private Ice.AsyncResult begin_appendString(String toAppend, 
                                               java.util.Map<String, String> __ctx, 
                                               boolean __explicitCtx, 
                                               boolean __synchronous, 
                                               IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__appendString_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__appendString_name, __cb);
        try
        {
            __result.prepare(__appendString_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(toAppend);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_appendString(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __appendString_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __appendString_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        Zad1.IEchoPrx __proxy = (Zad1.IEchoPrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_appendString(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __removeLastLetter_name = "removeLastLetter";

    public String removeLastLetter()
    {
        return removeLastLetter(null, false);
    }

    public String removeLastLetter(java.util.Map<String, String> __ctx)
    {
        return removeLastLetter(__ctx, true);
    }

    private String removeLastLetter(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__removeLastLetter_name);
        return end_removeLastLetter(begin_removeLastLetter(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_removeLastLetter()
    {
        return begin_removeLastLetter(null, false, false, null);
    }

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx)
    {
        return begin_removeLastLetter(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_removeLastLetter(Ice.Callback __cb)
    {
        return begin_removeLastLetter(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_removeLastLetter(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_removeLastLetter(Callback_IEcho_removeLastLetter __cb)
    {
        return begin_removeLastLetter(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, Callback_IEcho_removeLastLetter __cb)
    {
        return begin_removeLastLetter(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_removeLastLetter(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_removeLastLetter(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_removeLastLetter(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_removeLastLetter(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_removeLastLetter(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_removeLastLetter(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_removeLastLetter(__ctx, __explicitCtx, __synchronous, 
                                      new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                          {
                                              public final void __completed(Ice.AsyncResult __result)
                                              {
                                                  IEchoPrxHelper.__removeLastLetter_completed(this, __result);
                                              }
                                          });
    }

    private Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__removeLastLetter_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__removeLastLetter_name, __cb);
        try
        {
            __result.prepare(__removeLastLetter_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_removeLastLetter(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __removeLastLetter_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __removeLastLetter_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        Zad1.IEchoPrx __proxy = (Zad1.IEchoPrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_removeLastLetter(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IEchoPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), IEchoPrx.class, IEchoPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IEchoPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), IEchoPrx.class, IEchoPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IEchoPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), IEchoPrx.class, IEchoPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static IEchoPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), IEchoPrx.class, IEchoPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static IEchoPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, IEchoPrx.class, IEchoPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static IEchoPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, IEchoPrx.class, IEchoPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::Zad1::IEcho"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, IEchoPrx v)
    {
        __os.writeProxy(v);
    }

    public static IEchoPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            IEchoPrxHelper result = new IEchoPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
