// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Zad1.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Zad1;

public interface IEchoPrx extends Ice.ObjectPrx
{
    public String removeLastLetter();

    public String removeLastLetter(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeLastLetter();

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeLastLetter(Ice.Callback __cb);

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeLastLetter(Callback_IEcho_removeLastLetter __cb);

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, Callback_IEcho_removeLastLetter __cb);

    public Ice.AsyncResult begin_removeLastLetter(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeLastLetter(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeLastLetter(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public String end_removeLastLetter(Ice.AsyncResult __result);

    public String appendString(String toAppend);

    public String appendString(String toAppend, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appendString(String toAppend);

    public Ice.AsyncResult begin_appendString(String toAppend, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appendString(String toAppend, Ice.Callback __cb);

    public Ice.AsyncResult begin_appendString(String toAppend, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_appendString(String toAppend, Callback_IEcho_appendString __cb);

    public Ice.AsyncResult begin_appendString(String toAppend, java.util.Map<String, String> __ctx, Callback_IEcho_appendString __cb);

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appendString(String toAppend, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public String end_appendString(Ice.AsyncResult __result);
}
